### ISSUE TITLE
Grade sync does not import users if they already exist in the system

### ISSUE THREAD

**Issue by wynnset** [ubc/iPeer#594]
As reported by Tim Kato, this is an unexpected behavior that needs to be fixed. 

Steps to reproduce:
1. Access a course on iPeer (or create one) that is linked with a Canvas course and ensure some (or all) of the users from the Canvas course are also in the iPeer course.
2. Try to export the grades to Canvas.
3. You should get an error

Fix required:
- In the group controller imporCanvasGroups() function (see [here](https://github.com/ubc/iPeer/blob/1b3dd75e2bd5d65a4324167ac93d8f28feb02373/app/controllers/groups_controller.php#L1127)), we are not taking the case when a user is already in iPeer into account. Instead, we are attempting to create all the users in iPeer. This is why it's failing. 
- We need to check to see if the user is in iPeer already, and adjust the import process accordingly.

**Comment by kitsook** [comment]
The grade sync issue is caused by iPeer failed to (1) create Canvas assignment, and (2) post grades.

With fd07a32, when calling POST methods on Canvas APIs, parameters need to be in nested JSON format.

As for the group import issue, there was a typo in the array key.  Should be `updated_users` instead of `updated_students`:
https://github.com/ubc/iPeer/blob/1b3dd75e2bd5d65a4324167ac93d8f28feb02373/app/controllers/groups_controller.php#L1134-L1136
